Repository AY2223S1-CS2103T-W08-2/tp, pull requests merged in 2022-10, with the labels that each got.

#48 Ui: Add navigation between main panels
  src/main/java/seedu/address/logic/commands/BackCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/DetailHelpPanel.java
  src/main/java/seedu/address/ui/DetailPanel.java
  src/main/java/seedu/address/ui/HelpPanel.java
  src/main/java/seedu/address/ui/MainPanel.java
  src/main/java/seedu/address/ui/MainPanelName.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/DetailHelpPanel.fxml
  src/main/resources/view/DetailPanel.fxml
  src/main/resources/view/HelpPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/BackCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Task

#49 Ui: Improve abstraction in PersonListPanel
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
Labels: type.Enhancement

#58 Ui: Contact detail page
  src/main/java/seedu/address/ui/ContactBox.java
  src/main/java/seedu/address/ui/DetailPanel.java
  src/main/resources/images/contact/email.png
  src/main/resources/images/contact/slack.png
  src/main/resources/images/contact/telegram.png
  src/main/resources/images/contact/twitter.png
  src/main/resources/images/user_placeholder.png
  src/main/resources/view/ContactBox.fxml
  src/main/resources/view/DetailPanel.fxml
  src/main/resources/view/LightTheme.css
Labels: type.Task

#55 Add elements for help page
  src/main/resources/view/DetailHelpPanel.fxml
  src/main/resources/view/HelpPanel.fxml
Labels: type.Task

#79 Command: Categorize commands into different main panel
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/BackCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: type.Task

#67 Ui: Integrate contact into contact detail panel
  src/main/java/seedu/address/ui/ContactBox.java
  src/main/java/seedu/address/ui/DetailPanel.java
  src/main/resources/view/ContactBox.fxml
Labels: type.Task

#80 Remove phone and email attributes
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/TestFxmlObject.java
Labels: type.Task

#86 Remove all email and phone from UI
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
Labels: type.Task

#90 Storage: Add contacts to Person
  src/main/java/seedu/address/storage/JsonAdaptedContact.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task

#91 Add set command
  src/main/java/seedu/address/logic/commands/SetCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SetCommandParser.java
  src/main/java/seedu/address/ui/DetailPanel.java
  src/main/resources/images/contact/phone.png
Labels: type.Task

#95 Icons: Standardize design for contacts
  src/main/resources/images/contact/email.png
  src/main/resources/images/contact/github.png
  src/main/resources/images/contact/slack.png
  src/main/resources/images/contact/telegram.png
  src/main/resources/images/contact/twitter.png
Labels: type.Enhancement

#94 logic: include tags in SetCommand
  src/main/java/seedu/address/logic/commands/SetCommand.java
Labels: type.Bug

#100 Update NFR
  docs/DeveloperGuide.md
Labels: type.Task

#98 Command: Update cli syntax
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: type.Bug

#99 Ui: Update Ui styles
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/images/contact/email.png
  src/main/resources/images/contact/phone.png
  src/main/resources/images/contact/slack.png
  src/main/resources/images/contact/telegram.png
  src/main/resources/view/ContactBox.fxml
  src/main/resources/view/DetailPanel.fxml
  src/main/resources/view/HelpPanel.fxml
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Enhancement

#102 Model: Fix telegram link
  src/main/java/seedu/address/model/person/contact/Telegram.java
Labels: type.Task

#117 DG: Update Ui
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: type.Task

#104 Ui: Fix person list panel ui
  src/main/resources/view/LightTheme.css
Labels: type.Enhancement

#114 Docs: Update ui.png
  docs/images/Ui.png
Labels: type.Task

#116 Ui: Add logging to ContactBox
  src/main/java/seedu/address/ui/ContactBox.java
Labels: type.Enhancement

#103 Command: Change list to reset command
  src/main/java/seedu/address/logic/commands/ResetCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ResetCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Task

#127 Model: Make role and timezone optional
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/SetCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Role.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/SetPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task

#135 Ui: Add esc binding
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Enhancement, type.Task, priority.Low

#136 Docs: Update UserGuide
  docs/UserGuide.md
Labels: type.Enhancement, type.Task, priority.Low

#142 Test: Add tests person's attributes
  src/main/java/seedu/address/model/person/Role.java
  src/main/java/seedu/address/model/person/Timezone.java
  src/test/java/seedu/address/model/person/RoleTest.java
  src/test/java/seedu/address/model/person/TimezoneTest.java
  src/test/java/seedu/address/model/person/contact/EmailTest.java
  src/test/java/seedu/address/model/person/contact/PhoneTest.java
  src/test/java/seedu/address/model/person/contact/SlackTest.java
  src/test/java/seedu/address/model/person/contact/TelegramTest.java
  src/test/java/seedu/address/testutil/ContactUtil.java
Labels: type.Enhancement, type.Task, priority.Low

#139 Model: sort person list
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Enhancement, type.Task, priority.Low

#145 Logic: Improve HelpCommand
  src/main/java/seedu/address/logic/commands/BackCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ResetCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Enhancement, priority.Low

#138 Logic: Add alias to prefix
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/Prefix.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
Labels: type.Enhancement, type.Task, priority.Low

#146 Command: Sort command
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/PersonComparators.java
  src/main/java/seedu/address/model/person/Role.java
Labels: type.Task, priority.High

#141 Add GitHub API Wrapper
  build.gradle
  src/main/java/seedu/address/github/GithubApi.java
  src/main/java/seedu/address/github/UserInfoRoute.java
  src/main/java/seedu/address/github/UserInfoWrapper.java
  src/main/java/seedu/address/github/UserReposRoute.java
  src/main/java/seedu/address/github/UserReposWrapper.java
  src/main/java/seedu/address/github/exceptions/FileSaveFailException.java
  src/main/java/seedu/address/github/exceptions/NetworkConnectionException.java
  src/main/java/seedu/address/github/exceptions/RepoNotFoundException.java
  src/main/java/seedu/address/github/exceptions/ResponseParseException.java
  src/main/java/seedu/address/github/exceptions/UserInvalidException.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/github/User.java
  src/main/java/seedu/address/model/person/github/repo/Repo.java
  src/main/java/seedu/address/model/person/github/repo/RepoList.java
Labels: type.Task, priority.High

#157 Resources: Updated icons
  src/main/resources/images/contact/email.png
  src/main/resources/images/contact/phone.png
  src/main/resources/images/contact/telegram.png
Labels: type.Enhancement, priority.Low

#162 UG: Add github command
  docs/UserGuide.md
Labels: type.Enhancement, priority.Low

#174 Remove RepoList and Repo Forks
  src/main/java/seedu/address/github/UserReposWrapper.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/github/Repo.java
  src/main/java/seedu/address/model/person/github/User.java
  src/main/java/seedu/address/model/person/github/repo/RepoList.java
  src/main/java/seedu/address/storage/JsonAdaptedGithubRepo.java
  src/main/java/seedu/address/storage/JsonAdaptedGithubUser.java
Labels: type.Task, priority.Medium

#169 Command: Fix sort command
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/resources/view/HelpPanel.fxml
Labels: type.Bug

#221 GithubApi: Fix handling of API errors
  src/main/java/seedu/address/github/GithubApi.java
  src/main/java/seedu/address/model/person/github/User.java
Labels: type.Bug, priority.Medium

#220 Parser: Add message for invalid argument
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SetCommandParserTest.java
Labels: type.Bug, priority.Low

#222 Command: Fix BackCommand result
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, priority.Low

#173 Ui: Integrate GitHub into UI
  build.gradle
  src/main/java/seedu/address/ui/DetailPanel.java
  src/main/java/seedu/address/ui/GithubRepoCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/DetailPanel.fxml
  src/main/resources/view/GithubRepoCard.fxml
  src/main/resources/view/LightTheme.css
Labels: type.Task, priority.High

#226 Ui: Improvement
  src/main/java/seedu/address/ui/DetailPanel.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DetailPanel.fxml
  src/main/resources/view/LightTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: type.Enhancement, priority.High

#224 Logic: Add message for invalid command at specified page
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: type.Bug, priority.Low

#223 Ui: Improve Ui interaction
  docs/UserGuide.md
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/DetailPanel.java
  src/main/java/seedu/address/ui/GithubRepoCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/view/DetailPanel.fxml
  src/main/resources/view/GithubRepoCard.fxml
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatusBarFooter.fxml
Labels: type.Enhancement, priority.Medium

#227 Fix Set Command to work for github only commands
  src/main/java/seedu/address/logic/parser/SetCommandParser.java
Labels: type.Bug, severity.High
