Repository AY2223S1-CS2103T-W08-2/tp, pull requests merged in 2022-11, with the labels that each got.

#229 Fix User image download and User set logic
  src/main/java/seedu/address/github/GithubApi.java
  src/main/java/seedu/address/github/UserInfoWrapper.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/github/User.java
Labels: type.Bug, priority.High

#240 Model: Update Model interface
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ResetCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/SetCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
Labels: type.Task, priority.Medium

#239 Docs: Update developer guide
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/SortSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/SortSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/ug/detail_step3.png
Labels: type.Task, priority.Medium

#232 docs: Update Tang Zhi Lin's PPP
  docs/team/tex-tang.md
Labels: priority.Low

#244 Config: Update jar name in build.gradle
  build.gradle
Labels: type.Task, priority.Low

#247 Tests: Add RepoTest
  src/main/java/seedu/address/model/person/github/Repo.java
  src/test/java/seedu/address/model/person/github/RepoTest.java
  src/test/java/seedu/address/model/person/github/repo/RepoTest.java
Labels: type.Task, priority.Low

#248 Docs: Update Tang Zhi Lin's PPP
  docs/team/tex-tang.md
Labels: type.Task, priority.Low

#253 Add to Arnav PPP
  docs/team/arnav-ag.md
Labels: priority.Medium

#261 Docs: Update Developer Guide and User Guide
  docs/team/sh4nh.md
  src/main/java/seedu/address/model/person/PersonMatchesKeywordsPredicate.java
Labels: type.Task, priority.Low
